### ISSUE TITLE
zipfile.BadZipFile error running fab get_cases_from_bulk for non-whitelisted data

### ISSUE THREAD

**Issue by aculich** [harvard-lil/cap-examples#19]
I can download the whitelisted data fine, however after copying `config/settings.example.py` to `config/settings.py` and adding my API key, on other states such as `fab get_cases_from_bulk:Alaska` I get this error: `zipfile.BadZipFile: File is not a zip file`. See below for the full stacktrace.

If there were a problem with my API key I would hope to get an error accordingly.

When I run `fab get_cases_from_bulk:alaska` or something I know does not exist `fab get_cases_from_bulk:notajurisdiction` I get the error `Exception: Jurisdiction not found. Please check spelling.` so it seems the `fab get_cases_from_bulk:Alaska` is found, but there's a problem downloading.

I forked your repo here: https://github.com/aculich/cap-examples

And modified the requirements.txt to try running on binder (since there was a failure with the specific certifi dependency):

https://mybinder.org/v2/gh/aculich/cap-examples/master

I'm using Python 3.6 (instead of the 3.5.4 mentioned your docs).

Full Stacktrace:

```
Traceback (most recent call last):
  File "/srv/conda/lib/python3.6/site-packages/fabric/main.py", line 763, in main
    *args, **kwargs
  File "/srv/conda/lib/python3.6/site-packages/fabric/tasks.py", line 427, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/srv/conda/lib/python3.6/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/jovyan/fabfile.py", line 33, in get_cases_from_bulk
    utils.get_cases_from_bulk(jurisdiction)
  File "/home/jovyan/utils.py", line 50, in get_cases_from_bulk
    z = zipfile.ZipFile(io.BytesIO(r.content))
  File "/srv/conda/lib/python3.6/zipfile.py", line 1108, in __init__
    self._RealGetContents()
  File "/srv/conda/lib/python3.6/zipfile.py", line 1175, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by anastasia** [comment]
Hey @aculich, thank you for taking a look! 
We're working to fix this problem — it's looking like writing of some large files is getting interrupted partway through (hence the "BadZipFile" error).

**Comment by anastasia** [comment]
This issue should be fixed. Please let us know if it persists. Closing for now.

**Comment by aculich** [comment]
Thanks! I've confirmed that I can download the non-whitelisted jurisdictions now.

We appreciate the quick fix!
